### ISSUE TITLE
LaunchDarkly JavaScript SDK v2.20.0 is nearing end-of-life

### ISSUE THREAD

**Issue by jesse-schneider** [EvanBurbidge/vue-darkly#1]
Just wanted to check and see if there is any plan to update the LaunchDarkly SDK since the current one is soon to be end-of-life?

**Comment by thewebuiguy** [comment]
Hi @jesse-schneider sorry for the extremely late reply.... I will take a look into this but it's been quite a while since i've maintained this lib!

**Comment by jesse-schneider** [comment]
Hey @EvanBurbidge no worries at all, I ended up migrating to the offical package so no harm done 😄 absolutely live your life, no need to maintain things forever.

Thanks for the reply, appreciate it!

**Comment by thewebuiguy** [comment]
> 

No worries! I may mark this package as deprecated!
